node {
    cleanWs()
    checkout scm
    
    dir('gradle-artifactory-pipeline') {
        def rtGradle = Artifactory.newGradleBuild()
        rtGradle.deployer server: 'artifactory', repo: 'libs-release-local'

        def buildInfo = rtGradle.run rootDir: "tcp-client/", buildFile: 'build.gradle', tasks: 'clean build'
    }
}