node {
    cleanWs()
    checkout scm
    
    dir('gradle-artifactory-pipeline') {

        sh script: 'chmod +x tcp-client/gradlew'

        def rtGradle = Artifactory.newGradleBuild()
        rtGradle.useWrapper = true
        rtGradle.deployer server: Artifactory.server('artifactory'), repo: 'libs-release-local'

        def buildInfo = rtGradle.run rootDir: "tcp-client/", buildFile: 'build.gradle', tasks: 'clean artifactoryPublish''

        sh script: 'ls tcp-client'
    }
}