/*
 * This source file was generated by the Gradle 'init' task
 */
package com.yoav;

import com.yoav.TCPClient;

public class App {
    
    public static void main(String[] args) {
        TCPClient client = new TCPClient();
        client.openConnection();    
    }
}
